type CountryData = { country: string; timezones: string[] }[];

const countryData: CountryData = [
  { country: "Belarus", timezones: ["Europe/Minsk"] },
  { country: "UK", timezones: ["Europe/London"] },
  { country: "South Africa", timezones: ["Africa/Johannesburg"] },
  {
    country: "United States",
    timezones: [
      "America/Adak",
      "America/Anchorage",
      "America/Chicago",
      "America/Denver",
      "America/Indiana/Knox",
      "America/Los_Angeles",
    ],
  },
  { country: "Afghanistan", timezones: ["Asia/Kabul"] },
  { country: "Albania", timezones: ["Europe/Tirane"] },
  { country: "Algeria", timezones: ["Africa/Algiers"] },
  { country: "American Samoa", timezones: ["Pacific/Pago_Pago"] },
  { country: "Andorra", timezones: ["Europe/Andorra"] },
  { country: "Angola", timezones: ["Africa/Lagos"] },
  { country: "Anguilla", timezones: ["America/Puerto_Rico"] },
  {
    country: "Antarctica",
    timezones: [
      "Antarctica/Casey",
      "Antarctica/Davis",
      "Antarctica/Mawson",
      "Antarctica/Palmer",
      "Antarctica/Rothera",
      "Antarctica/Troll",
      "Antarctica/Vostok",
      "Asia/Riyadh",
      "Asia/Singapore",
      "Pacific/Auckland",
      "Pacific/Port_Moresby",
    ],
  },
  { country: "Antigua and Barbuda", timezones: ["America/Puerto_Rico"] },
  {
    country: "Argentina",
    timezones: [
      "America/Argentina/Buenos_Aires",
      "America/Argentina/Catamarca",
      "America/Argentina/Cordoba",
      "America/Argentina/Jujuy",
      "America/Argentina/La_Rioja",
      "America/Argentina/Mendoza",
      "America/Argentina/Rio_Gallegos",
      "America/Argentina/Salta",
      "America/Argentina/San_Juan",
      "America/Argentina/San_Luis",
      "America/Argentina/Tucuman",
      "America/Argentina/Ushuaia",
    ],
  },
  { country: "Armenia", timezones: ["Asia/Yerevan"] },
  { country: "Aruba", timezones: ["America/Puerto_Rico"] },
  {
    country: "Australia",
    timezones: [
      "Antarctica/Macquarie",
      "Asia/Tokyo",
      "Australia/Adelaide",
      "Australia/Brisbane",
      "Australia/Broken_Hill",
      "Australia/Darwin",
      "Australia/Eucla",
      "Australia/Hobart",
      "Australia/Lindeman",
      "Australia/Lord_Howe",
      "Australia/Melbourne",
      "Australia/Perth",
      "Australia/Sydney",
    ],
  },
  { country: "Austria", timezones: ["Europe/Vienna"] },
  { country: "Azerbaijan", timezones: ["Asia/Baku"] },
  { country: "Bahamas", timezones: ["America/Toronto"] },
  { country: "Bahrain", timezones: ["Asia/Qatar"] },
  { country: "Bangladesh", timezones: ["Asia/Dhaka"] },
  { country: "Barbados", timezones: ["America/Barbados"] },
  { country: "Belarus", timezones: ["Europe/Minsk"] },
  { country: "Belgium", timezones: ["Europe/Brussels"] },
  { country: "Belize", timezones: ["America/Belize"] },
  { country: "Benin", timezones: ["Africa/Lagos"] },
  { country: "Bermuda", timezones: ["Atlantic/Bermuda"] },
  { country: "Bhutan", timezones: ["Asia/Thimphu"] },
  { country: "Bolivia", timezones: ["America/La_Paz"] },
  { country: "Bosnia and Herzegovina", timezones: ["Europe/Belgrade"] },
  { country: "Botswana", timezones: ["Africa/Maputo"] },
  {
    country: "Brazil",
    timezones: [
      "America/Araguaina",
      "America/Bahia",
      "America/Belem",
      "America/Boa_Vista",
      "America/Campo_Grande",
      "America/Cuiaba",
      "America/Eirunepe",
      "America/Fortaleza",
      "America/Maceio",
      "America/Manaus",
      "America/Noronha",
      "America/Porto_Velho",
      "America/Recife",
      "America/Rio_Branco",
      "America/Santarem",
      "America/Sao_Paulo",
    ],
  },
  { country: "British Indian Ocean Territory", timezones: ["Indian/Chagos"] },
  { country: "Brunei", timezones: ["Asia/Kuching"] },
  { country: "Bulgaria", timezones: ["Europe/Sofia"] },
  { country: "Burkina Faso", timezones: ["Africa/Abidjan"] },
  { country: "Burundi", timezones: ["Africa/Maputo"] },
  { country: "Cabo Verde", timezones: ["Atlantic/Cape_Verde"] },
  { country: "Cambodia", timezones: ["Asia/Bangkok"] },
  { country: "Cameroon", timezones: ["Africa/Lagos"] },
  {
    country: "Canada",
    timezones: [
      "America/Cambridge_Bay",
      "America/Dawson",
      "America/Dawson_Creek",
      "America/Edmonton",
      "America/Fort_Nelson",
      "America/Glace_Bay",
      "America/Goose_Bay",
      "America/Halifax",
      "America/Inuvik",
      "America/Iqaluit",
      "America/Moncton",
      "America/Panama",
      "America/Phoenix",
      "America/Puerto_Rico",
      "America/Rankin_Inlet",
      "America/Regina",
      "America/Resolute",
      "America/St_Johns",
      "America/Swift_Current",
      "America/Toronto",
      "America/Vancouver",
      "America/Whitehorse",
      "America/Winnipeg",
    ],
  },
  { country: "Caribbean Netherlands", timezones: ["America/Puerto_Rico"] },
  { country: "Cayman Islands", timezones: ["America/Panama"] },
  { country: "Central African Republic", timezones: ["Africa/Lagos"] },
  { country: "Chad", timezones: ["Africa/Ndjamena"] },
  {
    country: "Chile",
    timezones: [
      "America/Coyhaique",
      "America/Punta_Arenas",
      "America/Santiago",
      "Pacific/Easter",
    ],
  },
  { country: "China", timezones: ["Asia/Shanghai", "Asia/Urumqi"] },
  { country: "Christmas Island", timezones: ["Asia/Bangkok"] },
  { country: "Cocos Islands", timezones: ["Asia/Yangon"] },
  { country: "Colombia", timezones: ["America/Bogota"] },
  { country: "Comoros", timezones: ["Africa/Nairobi"] },
  { country: "Cook Islands", timezones: ["Pacific/Rarotonga"] },
  { country: "Costa Rica", timezones: ["America/Costa_Rica"] },
  { country: "Croatia", timezones: ["Europe/Belgrade"] },
  { country: "Cuba", timezones: ["America/Havana"] },
  { country: "Curaçao", timezones: ["America/Puerto_Rico"] },
  { country: "Cyprus", timezones: ["Asia/Famagusta", "Asia/Nicosia"] },
  { country: "Czechia", timezones: ["Europe/Prague"] },
  {
    country: "Democratic Republic of the Congo",
    timezones: ["Africa/Lagos", "Africa/Maputo"],
  },
  { country: "Denmark", timezones: ["Europe/Berlin"] },
  { country: "Djibouti", timezones: ["Africa/Nairobi"] },
  { country: "Dominica", timezones: ["America/Puerto_Rico"] },
  { country: "Dominican Republic", timezones: ["America/Santo_Domingo"] },
  { country: "Ecuador", timezones: ["America/Guayaquil", "Pacific/Galapagos"] },
  { country: "Egypt", timezones: ["Africa/Cairo"] },
  { country: "El Salvador", timezones: ["America/El_Salvador"] },
  { country: "Equatorial Guinea", timezones: ["Africa/Lagos"] },
  { country: "Eritrea", timezones: ["Africa/Nairobi"] },
  { country: "Estonia", timezones: ["Europe/Tallinn"] },
  { country: "Eswatini", timezones: ["Africa/Johannesburg"] },
  { country: "Ethiopia", timezones: ["Africa/Nairobi"] },
  { country: "Falkland Islands", timezones: ["Atlantic/Stanley"] },
  { country: "Faroe Islands", timezones: ["Atlantic/Faroe"] },
  { country: "Fiji", timezones: ["Pacific/Fiji"] },
  { country: "Finland", timezones: ["Europe/Helsinki"] },
  { country: "France", timezones: ["Europe/Paris"] },
  { country: "French Guiana", timezones: ["America/Cayenne"] },
  {
    country: "French Polynesia",
    timezones: ["Pacific/Gambier", "Pacific/Marquesas", "Pacific/Tahiti"],
  },
  {
    country: "French Southern Territories",
    timezones: ["Asia/Dubai", "Indian/Maldives"],
  },
  { country: "Gabon", timezones: ["Africa/Lagos"] },
  { country: "Gambia", timezones: ["Africa/Abidjan"] },
  { country: "Georgia", timezones: ["Asia/Tbilisi"] },
  { country: "Germany", timezones: ["Europe/Berlin", "Europe/Zurich"] },
  { country: "Ghana", timezones: ["Africa/Abidjan"] },
  { country: "Gibraltar", timezones: ["Europe/Gibraltar"] },
  { country: "Greece", timezones: ["Europe/Athens"] },
  {
    country: "Greenland",
    timezones: [
      "America/Danmarkshavn",
      "America/Nuuk",
      "America/Scoresbysund",
      "America/Thule",
    ],
  },
  { country: "Grenada", timezones: ["America/Puerto_Rico"] },
  { country: "Guadeloupe", timezones: ["America/Puerto_Rico"] },
  { country: "Guam", timezones: ["Pacific/Guam"] },
  { country: "Guatemala", timezones: ["America/Guatemala"] },
  { country: "Guernsey", timezones: ["Europe/London"] },
  { country: "Guinea", timezones: ["Africa/Abidjan"] },
  { country: "Guinea-Bissau", timezones: ["Africa/Bissau"] },
  { country: "Guyana", timezones: ["America/Guyana"] },
  { country: "Haiti", timezones: ["America/Port-au-Prince"] },
  { country: "Holy See", timezones: ["Europe/Rome"] },
  { country: "Honduras", timezones: ["America/Tegucigalpa"] },
  { country: "Hong Kong", timezones: ["Asia/Hong_Kong"] },
  { country: "Hungary", timezones: ["Europe/Budapest"] },
  { country: "Iceland", timezones: ["Africa/Abidjan"] },
  { country: "India", timezones: ["Asia/Kolkata"] },
  {
    country: "Indonesia",
    timezones: [
      "Asia/Jakarta",
      "Asia/Jayapura",
      "Asia/Makassar",
      "Asia/Pontianak",
    ],
  },
  { country: "Iran", timezones: ["Asia/Tehran"] },
  { country: "Iraq", timezones: ["Asia/Baghdad"] },
  { country: "Ireland", timezones: ["Europe/Dublin"] },
  { country: "Isle of Man", timezones: ["Europe/London"] },
  { country: "Israel", timezones: ["Asia/Jerusalem"] },
  { country: "Italy", timezones: ["Europe/Rome"] },
  { country: "Ivory Coast", timezones: ["Africa/Abidjan"] },
  { country: "Jamaica", timezones: ["America/Jamaica"] },
  { country: "Japan", timezones: ["Asia/Tokyo"] },
  { country: "Jersey", timezones: ["Europe/London"] },
  { country: "Jordan", timezones: ["Asia/Amman"] },
  {
    country: "Kazakhstan",
    timezones: [
      "Asia/Almaty",
      "Asia/Aqtau",
      "Asia/Aqtobe",
      "Asia/Atyrau",
      "Asia/Oral",
      "Asia/Qostanay",
      "Asia/Qyzylorda",
    ],
  },
  { country: "Kenya", timezones: ["Africa/Nairobi"] },
  {
    country: "Kiribati",
    timezones: ["Pacific/Kanton", "Pacific/Kiritimati", "Pacific/Tarawa"],
  },
  { country: "Kuwait", timezones: ["Asia/Riyadh"] },
  { country: "Kyrgyzstan", timezones: ["Asia/Bishkek"] },
  { country: "Laos", timezones: ["Asia/Bangkok"] },
  { country: "Latvia", timezones: ["Europe/Riga"] },
  { country: "Lebanon", timezones: ["Asia/Beirut"] },
  { country: "Lesotho", timezones: ["Africa/Johannesburg"] },
  { country: "Liberia", timezones: ["Africa/Monrovia"] },
  { country: "Libya", timezones: ["Africa/Tripoli"] },
  { country: "Liechtenstein", timezones: ["Europe/Zurich"] },
  { country: "Lithuania", timezones: ["Europe/Vilnius"] },
  { country: "Luxembourg", timezones: ["Europe/Brussels"] },
  { country: "Macao", timezones: ["Asia/Macau"] },
  { country: "Madagascar", timezones: ["Africa/Nairobi"] },
  { country: "Malawi", timezones: ["Africa/Maputo"] },
  { country: "Malaysia", timezones: ["Asia/Kuching", "Asia/Singapore"] },
  { country: "Maldives", timezones: ["Indian/Maldives"] },
  { country: "Mali", timezones: ["Africa/Abidjan"] },
  { country: "Malta", timezones: ["Europe/Malta"] },
  {
    country: "Marshall Islands",
    timezones: ["Pacific/Kwajalein", "Pacific/Tarawa"],
  },
  { country: "Martinique", timezones: ["America/Martinique"] },
  { country: "Mauritania", timezones: ["Africa/Abidjan"] },
  { country: "Mauritius", timezones: ["Indian/Mauritius"] },
  { country: "Mayotte", timezones: ["Africa/Nairobi"] },
  {
    country: "Mexico",
    timezones: [
      "America/Bahia_Banderas",
      "America/Cancun",
      "America/Chihuahua",
      "America/Ciudad_Juarez",
      "America/Hermosillo",
      "America/Matamoros",
      "America/Mazatlan",
      "America/Merida",
      "America/Mexico_City",
      "America/Monterrey",
      "America/Ojinaga",
      "America/Tijuana",
    ],
  },
  {
    country: "Micronesia",
    timezones: [
      "Pacific/Guadalcanal",
      "Pacific/Kosrae",
      "Pacific/Port_Moresby",
    ],
  },
  { country: "Moldova", timezones: ["Europe/Chisinau"] },
  { country: "Monaco", timezones: ["Europe/Paris"] },
  { country: "Mongolia", timezones: ["Asia/Hovd", "Asia/Ulaanbaatar"] },
  { country: "Montenegro", timezones: ["Europe/Belgrade"] },
  { country: "Montserrat", timezones: ["America/Puerto_Rico"] },
  { country: "Morocco", timezones: ["Africa/Casablanca"] },
  { country: "Mozambique", timezones: ["Africa/Maputo"] },
  { country: "Myanmar", timezones: ["Asia/Yangon"] },
  { country: "Namibia", timezones: ["Africa/Windhoek"] },
  { country: "Nauru", timezones: ["Pacific/Nauru"] },
  { country: "Nepal", timezones: ["Asia/Kathmandu"] },
  { country: "Netherlands", timezones: ["Europe/Brussels"] },
  { country: "New Caledonia", timezones: ["Pacific/Noumea"] },
  {
    country: "New Zealand",
    timezones: ["Pacific/Auckland", "Pacific/Chatham"],
  },
  { country: "Nicaragua", timezones: ["America/Managua"] },
  { country: "Niger", timezones: ["Africa/Lagos"] },
  { country: "Nigeria", timezones: ["Africa/Lagos"] },
  { country: "Niue", timezones: ["Pacific/Niue"] },
  { country: "Norfolk Island", timezones: ["Pacific/Norfolk"] },
  { country: "North Korea", timezones: ["Asia/Pyongyang"] },
  { country: "North Macedonia", timezones: ["Europe/Belgrade"] },
  { country: "Northern Mariana Islands", timezones: ["Pacific/Guam"] },
  { country: "Norway", timezones: ["Europe/Berlin"] },
  { country: "Oman", timezones: ["Asia/Dubai"] },
  { country: "Pakistan", timezones: ["Asia/Karachi"] },
  { country: "Palau", timezones: ["Pacific/Palau"] },
  { country: "Palestine", timezones: ["Asia/Gaza", "Asia/Hebron"] },
  { country: "Panama", timezones: ["America/Panama"] },
  {
    country: "Papua New Guinea",
    timezones: ["Pacific/Bougainville", "Pacific/Port_Moresby"],
  },
  { country: "Paraguay", timezones: ["America/Asuncion"] },
  { country: "Peru", timezones: ["America/Lima"] },
  { country: "Philippines", timezones: ["Asia/Manila"] },
  { country: "Pitcairn", timezones: ["Pacific/Pitcairn"] },
  { country: "Poland", timezones: ["Europe/Warsaw"] },
  {
    country: "Portugal",
    timezones: ["Atlantic/Azores", "Atlantic/Madeira", "Europe/Lisbon"],
  },
  { country: "Puerto Rico", timezones: ["America/Puerto_Rico"] },
  { country: "Qatar", timezones: ["Asia/Qatar"] },
  { country: "Republic of the Congo", timezones: ["Africa/Lagos"] },
  { country: "Romania", timezones: ["Europe/Bucharest"] },
  {
    country: "Russia",
    timezones: [
      "Asia/Anadyr",
      "Asia/Barnaul",
      "Asia/Chita",
      "Asia/Irkutsk",
      "Asia/Kamchatka",
      "Asia/Khandyga",
      "Asia/Krasnoyarsk",
      "Asia/Magadan",
      "Asia/Novokuznetsk",
      "Asia/Novosibirsk",
      "Asia/Omsk",
      "Asia/Sakhalin",
      "Asia/Srednekolymsk",
      "Asia/Tomsk",
      "Asia/Ust-Nera",
      "Asia/Vladivostok",
      "Asia/Yakutsk",
      "Asia/Yekaterinburg",
      "Europe/Astrakhan",
      "Europe/Kaliningrad",
      "Europe/Kirov",
      "Europe/Moscow",
      "Europe/Samara",
      "Europe/Saratov",
      "Europe/Simferopol",
      "Europe/Ulyanovsk",
      "Europe/Volgograd",
    ],
  },
  { country: "Rwanda", timezones: ["Africa/Maputo"] },
  { country: "Réunion", timezones: ["Asia/Dubai"] },
  { country: "Saint Barthélemy", timezones: ["America/Puerto_Rico"] },
  {
    country: "Saint Helena, Ascension and Tristan da Cunha",
    timezones: ["Africa/Abidjan"],
  },
  { country: "Saint Kitts and Nevis", timezones: ["America/Puerto_Rico"] },
  { country: "Saint Lucia", timezones: ["America/Puerto_Rico"] },
  { country: "Saint Martin", timezones: ["America/Puerto_Rico"] },
  { country: "Saint Pierre and Miquelon", timezones: ["America/Miquelon"] },
  {
    country: "Saint Vincent and the Grenadines",
    timezones: ["America/Puerto_Rico"],
  },
  { country: "Samoa", timezones: ["Pacific/Apia"] },
  { country: "San Marino", timezones: ["Europe/Rome"] },
  { country: "Sao Tome and Principe", timezones: ["Africa/Sao_Tome"] },
  { country: "Saudi Arabia", timezones: ["Asia/Riyadh"] },
  { country: "Senegal", timezones: ["Africa/Abidjan"] },
  { country: "Serbia", timezones: ["Europe/Belgrade"] },
  { country: "Seychelles", timezones: ["Asia/Dubai"] },
  { country: "Sierra Leone", timezones: ["Africa/Abidjan"] },
  { country: "Singapore", timezones: ["Asia/Singapore"] },
  { country: "Sint Maarten", timezones: ["America/Puerto_Rico"] },
  { country: "Slovakia", timezones: ["Europe/Prague"] },
  { country: "Slovenia", timezones: ["Europe/Belgrade"] },
  { country: "Solomon Islands", timezones: ["Pacific/Guadalcanal"] },
  { country: "Somalia", timezones: ["Africa/Nairobi"] },
  { country: "South Africa", timezones: ["Africa/Johannesburg"] },
  {
    country: "South Georgia and the South Sandwich Islands",
    timezones: ["Atlantic/South_Georgia"],
  },
  { country: "South Korea", timezones: ["Asia/Seoul"] },
  { country: "South Sudan", timezones: ["Africa/Juba"] },
  {
    country: "Spain",
    timezones: ["Africa/Ceuta", "Atlantic/Canary", "Europe/Madrid"],
  },
  { country: "Sri Lanka", timezones: ["Asia/Colombo"] },
  { country: "Sudan", timezones: ["Africa/Khartoum"] },
  { country: "Suriname", timezones: ["America/Paramaribo"] },
  { country: "Svalbard and Jan Mayen", timezones: ["Europe/Berlin"] },
  { country: "Sweden", timezones: ["Europe/Berlin"] },
  { country: "Switzerland", timezones: ["Europe/Zurich"] },
  { country: "Syria", timezones: ["Asia/Damascus"] },
  { country: "Taiwan", timezones: ["Asia/Taipei"] },
  { country: "Tajikistan", timezones: ["Asia/Dushanbe"] },
  { country: "Tanzania", timezones: ["Africa/Nairobi"] },
  { country: "Thailand", timezones: ["Asia/Bangkok"] },
  { country: "Timor-Leste", timezones: ["Asia/Dili"] },
  { country: "Togo", timezones: ["Africa/Abidjan"] },
  { country: "Tokelau", timezones: ["Pacific/Fakaofo"] },
  { country: "Tonga", timezones: ["Pacific/Tongatapu"] },
  { country: "Trinidad and Tobago", timezones: ["America/Puerto_Rico"] },
  { country: "Tunisia", timezones: ["Africa/Tunis"] },
  { country: "Turkmenistan", timezones: ["Asia/Ashgabat"] },
  { country: "Turks and Caicos Islands", timezones: ["America/Grand_Turk"] },
  { country: "Tuvalu", timezones: ["Pacific/Tarawa"] },
  { country: "Türkiye", timezones: ["Europe/Istanbul"] },
  { country: "Uganda", timezones: ["Africa/Nairobi"] },
  { country: "Ukraine", timezones: ["Europe/Kyiv", "Europe/Simferopol"] },
  { country: "United Arab Emirates", timezones: ["Asia/Dubai"] },
  { country: "United Kingdom", timezones: ["Europe/London"] },
  {
    country: "United States Minor Outlying Islands",
    timezones: ["Pacific/Pago_Pago", "Pacific/Tarawa"],
  },
  {
    country: "United States of America",
    timezones: [
      "America/Adak",
      "America/Anchorage",
      "America/Boise",
      "America/Chicago",
      "America/Denver",
      "America/Detroit",
      "America/Indiana/Indianapolis",
      "America/Indiana/Knox",
      "America/Indiana/Marengo",
      "America/Indiana/Petersburg",
      "America/Indiana/Tell_City",
      "America/Indiana/Vevay",
      "America/Indiana/Vincennes",
      "America/Indiana/Winamac",
      "America/Juneau",
      "America/Kentucky/Louisville",
      "America/Kentucky/Monticello",
      "America/Los_Angeles",
      "America/Menominee",
      "America/Metlakatla",
      "America/New_York",
      "America/Nome",
      "America/North_Dakota/Beulah",
      "America/North_Dakota/Center",
      "America/North_Dakota/New_Salem",
      "America/Phoenix",
      "America/Sitka",
      "America/Yakutat",
      "Pacific/Honolulu",
    ],
  },
  { country: "Uruguay", timezones: ["America/Montevideo"] },
  { country: "Uzbekistan", timezones: ["Asia/Samarkand", "Asia/Tashkent"] },
  { country: "Vanuatu", timezones: ["Pacific/Efate"] },
  { country: "Venezuela", timezones: ["America/Caracas"] },
  { country: "Vietnam", timezones: ["Asia/Bangkok", "Asia/Ho_Chi_Minh"] },
  { country: "Virgin Islands (UK)", timezones: ["America/Puerto_Rico"] },
  { country: "Virgin Islands (US)", timezones: ["America/Puerto_Rico"] },
  { country: "Wallis and Futuna", timezones: ["Pacific/Tarawa"] },
  { country: "Western Sahara", timezones: ["Africa/El_Aaiun"] },
  { country: "Yemen", timezones: ["Asia/Riyadh"] },
  { country: "Zambia", timezones: ["Africa/Maputo"] },
  { country: "Zimbabwe", timezones: ["Africa/Maputo"] },
  { country: "Åland Islands", timezones: ["Europe/Helsinki"] },
];

export default countryData;
